[package]
name = "revopoint-pop3-wifi"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Provision Revopoint POP 3 Wi-Fi credentials over USB on Linux"
repository = "https://github.com/TamedTornado/revopoint-pop3-linux-wifi"

[features]
default = []
ros2 = ["dep:rclrs"]

[dependencies]
jpeg-decoder = { version = "=0.3.2", default-features = false }
quicklz = "=0.3.1"
rclrs = { version = "=0.7.0", optional = true }
rpassword = "7.3.1"
rusb = "0.9.4"
